class Commands:
    PLAY = "START"
    PLAYING = "PLAYING"
    PAUSE = "PAUSE"
    STOP = "STOP"
    COMMAND = "command"
    BPM = "bpm"
    SCALE = "scale"
    PROMPT = "prompt"
    WEIGHT = "weight"
